#!/usr/bin/env node
/**
 * Stop hook (strict): runs the project's configured verification commands on
 * stop (lint, types). On a real failure it blocks so Claude fixes it before
 * finishing. Generated by aia-harness — fail-open on infra: a missing runtime
 * or command never blocks. Re-run /aia-harness:doctor to audit.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execSync } from 'node:child_process';

const COMMANDS = [
  { label: 'lint', cmd: 'npm run lint' },
  { label: 'typecheck', cmd: 'npx tsc --noEmit' },
  { label: 'test', cmd: 'npm test' },
];
const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();
const LINTABLE = /\.(js|jsx|ts|tsx|mjs|cjs|vue|svelte|php)$/;

function flagFile() {
  const h = createHash('sha1').update(projectDir).digest('hex').slice(0, 12);
  return path.join(os.tmpdir(), 'aia-harness-changed-' + h);
}
function clearFlag() {
  try {
    fs.rmSync(flagFile(), { force: true });
  } catch (e) {
    /* ignore */
  }
}
function approve() {
  process.stdout.write(JSON.stringify({ decision: 'approve' }));
  process.exit(0);
}

let event = {};
try {
  event = JSON.parse(fs.readFileSync(0, 'utf8') || '{}');
} catch (e) {
  process.exit(0);
}

// Anti-loop: a stop already triggered by a previous block must be allowed.
if (event && event.stop_hook_active) {
  clearFlag();
  approve();
}

const flag = flagFile();
if (!fs.existsSync(flag)) approve(); // session changed nothing

let changed = '';
try {
  changed = fs.readFileSync(flag, 'utf8');
} catch (e) {
  approve();
}
const hasLintable = changed.split('\n').some(function (p) {
  return LINTABLE.test(p.trim());
});
if (!hasLintable) {
  clearFlag();
  approve();
}

// Ensure the active node's dir (nvm/fnm/system node) is on PATH for the run.
// process.execPath is always the actual running binary — works with any node manager.
const binDir = path.dirname(process.execPath);
const env = Object.assign({}, process.env, {
  PATH: binDir + path.delimiter + (process.env.PATH || ''),
});

const failures = [];
for (const entry of COMMANDS) {
  try {
    execSync(entry.cmd, {
      cwd: projectDir,
      env: env,
      timeout: 120000,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } catch (err) {
    // ENOENT / exit 127 = command or runtime missing -> infra, fail open.
    if (err.code === 'ENOENT' || err.status === 127) continue;
    const out = (
      (err.stdout ? err.stdout.toString() : '') + (err.stderr ? err.stderr.toString() : '')
    ).trim();
    failures.push({
      label: entry.label,
      cmd: entry.cmd,
      out: out || err.message || entry.label + ' failed',
    });
  }
}

if (failures.length === 0) {
  clearFlag();
  approve();
}

let lines = [];
for (const f of failures) {
  lines.push('=== ' + f.label + ' (' + f.cmd + ') failed ===');
  lines = lines.concat(f.out.split('\n'));
  lines.push('');
}
const excerpt = lines.slice(0, 80).join('\n');
const truncated = lines.length > 80 ? '\n...(' + (lines.length - 80) + ' more lines)' : '';

process.stdout.write(
  JSON.stringify({
    decision: 'block',
    reason: 'Fix all lint/type errors below before finishing.\n\n' + excerpt + truncated,
    hookSpecificOutput: {
      hookEventName: 'Stop',
      additionalContext:
        'Failed verification: ' +
        failures
          .map(function (f) {
            return f.cmd;
          })
          .join(', '),
    },
  })
);
process.exit(0);
