import Anthropic from '@anthropic-ai/sdk';
import Groq from 'groq-sdk';
import OpenAI from 'openai';
import { logger } from '../utils/logger.js';

interface AIConfig {
    provider: string;
    model: string;
    apiKey: string;
    language: string;
}

export class AIService {
    private config: AIConfig;
    private openai?: OpenAI;
    private groq?: Groq;
    private anthropic?: Anthropic;

    constructor(config: AIConfig) {
        this.config = config;
        this.initializeClient();
    }

    private initializeClient() {
        switch (this.config.provider) {
            case 'openai':
                this.openai = new OpenAI({ apiKey: this.config.apiKey });
                break;
            case 'groq':
                this.groq = new Groq({ apiKey: this.config.apiKey });
                break;
            case 'anthropic':
                this.anthropic = new Anthropic({ apiKey: this.config.apiKey });
                break;
            default:
                logger.error(`Provider ${this.config.provider} is not supported.`);
                process.exit(1);
        }
    }

    private getCommitSystemPrompt(): string {
        return `
You are an assistant that helps generate commit messages for a Git repository.
Commit messages must follow the Conventional Commits standard, which uses ONLY these specific prefixes to categorize the type of change made: feat, fix, docs, chore.
The description must be concise and clear, explaining what was done, the reason for the change, and, if applicable, the impact of the change.
The messages must be generated based on the changes provided by the 'git diff' command and an optional basic description provided by the user.

Mandatory rules:
- DO NOT add any comments or additional explanations beyond the generated commit message.
- DO NOT use symbols such as \`\`\` or any other formatting to denote the commit message.
- DO NOT add line breaks or whitespace before the commit message.
- The output must be ONLY the final commit message as per the instructions.
- The first line of the message must start with one of these EXACT prefixes: feat, fix, docs, chore.
- After the first line, always add an objective explanation of the changes made, the reason for the change, and, if applicable, the impact of the change.

<output_format>
CRITICAL: Your response must follow this exact structure:

Line 1: [prefix]: [concise description]
(where prefix must be exactly one of: feat, fix, docs, chore)
Line 2: [EMPTY LINE - mandatory line break]
Line 3+: [detailed explanation]

CORRECT format example:
feat: add user authentication system

Implement JWT-based authentication with login and registration endpoints. Add middleware for route protection and user session management. This enhancement improves application security and enables personalized user experiences.

INCORRECT format (everything in one line):
feat: add user authentication system - Implement JWT-based authentication with login and registration endpoints...
</output_format>

If the instructions are not followed correctly, the result will not be accepted.
`.trim();
    }

    private getCommitUserPrompt(diffOutput: string, projectLanguage: string, baseMessage: string): string {
        return `
Based on the information provided below, create a commit message following the Conventional Commits standard.

The ONLY accepted prefixes for this project are:
    - feat: A new feature
    - fix: A bug fix
    - docs: Documentation changes
    - chore: Maintenance changes or minor fixes that do not alter functionality

For your information and better understanding, the project in question uses the programming language ${projectLanguage}.

Basic change description provided by the developer, which you should use as the basis for your message: '${baseMessage}'

Below are the detailed changes (including modified files and what was added, changed, or removed) generated by the 'git diff' command:

\`\`\`
${diffOutput}
\`\`\`

Based on the above information, improve the basic description to create an objective commit message.
Mandatory rules:
- You must follow the Conventional Commits standard.
- The first line of the message must start with one of these EXACT prefixes (feat, fix, docs, chore) followed by a concise description explaining what was done.
- After the first line, always add an objective explanation of the changes made, the reason for the change, and, if applicable, the impact of the change.
- Whenever possible, mention only the main modified files in the commit message without including the path.
- DO NOT add any comments or additional explanations beyond the generated commit message.
- DO NOT use symbols such as \`\`\` or any other formatting to denote the commit message.
- DO NOT add line breaks or whitespace before the commit message.
- The output must be ONLY the final commit message as per the instructions.
- You must use the language '${this.config.language}' in your response generation.

<output_format>
Your response must follow this exact format:

Line 1: [prefix]: [concise description]
Line 2: [empty line]
Line 3+: [detailed explanation of changes, reasons, and impact]
</output_format>
`.trim();
    }

    async generateCommitMessage(diffOutput: string, projectLanguage: string, baseMessage: string): Promise<string> {
        const systemPrompt = this.getCommitSystemPrompt();
        const userPrompt = this.getCommitUserPrompt(diffOutput, projectLanguage, baseMessage);
        
        return this.callApi(systemPrompt, userPrompt);
    }
    
    // Logic for release notes (used by releaser.ts)
    async generateReleaseNotes(commits: string, newVersion: string, tag: string): Promise<string> {
         const systemPrompt = `
You are an assistant that helps generate release notes for a Git repository.
Commit messages should be organized into categories such as New Features, Bug Fixes, and Other Changes.
The output must be a markdown-formatted text according to the provided template, with no additional comments or formatting.
`.trim();
        
        const userPrompt = `
You are an assistant that helps generate release notes for a Git repository.
Below are the commits since the last tag ${tag}.
Please organize the commits into the following categories: New Features, Bug Fixes, and Other Changes.
Generate a release message in markdown format in the language '${this.config.language}' using the following template:

\`\`\`
# Release ${newVersion}
<SUMMARY/>

### New Features
- Description of new features (commits).

### Bug Fixes
- Description of bug fixes (commits).

### Other Changes
- Description of other changes (commits).

We thank all the contributors who made this release possible! For more details, please refer to the complete version notes.

**Full Changelog:** [See commits for ${newVersion}](https://github.com/leandrosilvaferreira/gitai/compare/${tag}...${newVersion})
\`\`\`

Commits:
${commits}

Important rules:
    - The generated content must be in the language '${this.config.language}'.
    - Replace <SUMMARY/> in the template with a brief and enthusiastic summary of the changes made since the last tag ${tag}.
    - DO NOT add any additional comments or explanations.
    - DO NOT use symbols like \`\`\` to denote commit messages.
    - The message must be clear, concise, and well-organized.
    - Remember to follow the provided template.

If the instructions are not followed correctly, the result will not be accepted.
`.trim();

        return this.callApi(systemPrompt, userPrompt);

    }


    private async callApi(systemPrompt: string, userPrompt: string): Promise<string> {
        if (this.config.provider === 'openai' && this.openai) {
            logger.ai(`Provider: openai - Model: ${this.config.model}`);
            
            const isNewModel = ['o1', 'o3', 'gpt-5'].some(prefix => this.config.model.startsWith(prefix));
            const tokenParam = isNewModel ? 'max_completion_tokens' : 'max_tokens';
            
            const completion = await this.openai.chat.completions.create({
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userPrompt }
                ],
                model: this.config.model,
                temperature: 0.5,
                top_p: 1.0,
                frequency_penalty: 0.0,
                presence_penalty: 0.0,
                [tokenParam]: 500,
            } as any);

            return completion.choices[0].message.content?.trim() || '';

        } else if (this.config.provider === 'groq' && this.groq) {
             logger.ai(`Provider: groq - Model: ${this.config.model}`);
             const completion = await this.groq.chat.completions.create({
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userPrompt }
                ],
                model: this.config.model,
                temperature: 0.5,
                max_tokens: 500,
                top_p: 1.0,
                frequency_penalty: 0.0,
                presence_penalty: 0.0
            });
            return completion.choices[0].message.content?.trim() || '';

        } else if (this.config.provider === 'anthropic' && this.anthropic) {
            logger.ai(`Provider: anthropic - Model: ${this.config.model}`);
            const message = await this.anthropic.messages.create({
                model: this.config.model,
                max_tokens: 500,
                temperature: 0.5,
                system: systemPrompt,
                messages: [
                    { role: 'user', content: userPrompt }
                ]
            });
            return (message.content[0] as any).text.trim();
        }

        return '';
    }
}
