#!/usr/bin/env bash
# Generated by aia-harness — reference for project TOOLS + MCP servers.
# Review every line before running. Nothing here runs automatically.
# Plugins are installed separately — run scripts/install-plugins.sh (it is runnable),
# or let /aia-harness:init offer them interactively.
set -euo pipefail

# --- Project-level tools ----------------------------------------------------
#   vendored into .claude/ (no machine install needed): rtk, claude-code-worktrees
#   rtk (token proxy) — PreToolUse hook already wired (guarded). Install the binary:
#     brew install rtk   # or: curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/refs/heads/master/install.sh | sh
#   graphify (code graph) — project-level:
#     uv tool install graphifyy        # instala o binário graphify
#     graphify install --project       # registra a skill no .claude/skills/graphify/
#     graphify .                       # constrói o grafo inicial
#     git add graphify-out/ && git commit -m 'chore: add graphify code graph'

# --- MCP servers ------------------------------------------------------------
# The following strategic MCP servers were written to .mcp.json:
#   - context7
#   - sequential-thinking
#   - github
#
# Fill required secrets in .claude/settings.local.json (gitignored), then
# restart Claude Code so MCP servers load.

echo "Reference only. Plugins: run scripts/install-plugins.sh. Tools: uncomment a command above and re-run."
